default: &default
  adapter: postgresql
  encoding: utf-8
  host:  <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER_NAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: 5432

development:
  <<: *default
  database: survey_app_development